title: "Kyle Brown — Aerospace Portfolio"
name: "Kyle Brown"
description: "UAV systems, propulsion, CAD design, and mission design."
theme: null
remote_theme: "mmistakes/minimal-mistakes"

url: "https://kylebrown978.github.io"
baseurl: ""  # keep empty for username.github.io root site

# Navigation
nav:
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/

# Author block
author:
  name: "Kyle Brown"
  bio: "UAV systems, propulsion, CAD design, and mission design."
  links:
    - label: LinkedIn
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kyle-v-brown"
    - label: Email
      icon: "fas fa-envelope"
      url: "mailto:Kylebrown978@yahoo.com"
    - label: Résumé
      icon: "fas fa-file"
      url: "/assets/pdf/Kyle_Brown_Resume.pdf"

# Collections for projects
collections:
  projects:
    output: true
defaults:
  - scope: { path: "", type: projects }
    values:
      layout: single
      classes: wide
      author_profile: true
